### ISSUE TITLE
Attempt to index field 'info' (a boolean value)

### ISSUE THREAD

**Issue by nikoroxy** [wrxck/telegram-bot-lua#11] opened 2019-01-10 12:03 UTC
When I try to initialize an instance I get this:

```
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> local api = require('telegram-bot-lua.core').configure('bot*bottoken*')

Not Found [404]

Payload: [""]

/usr/local/share/lua/5.1/telegram-bot-lua/core.lua:32: attempt to index field 'info' (a boolean value)
stack traceback:
        /usr/local/share/lua/5.1/telegram-bot-lua/core.lua:32: in function 'configure'
        stdin:1: in main chunk
        [C]: ?
```

Why the 404 error?

**Comment by wrxck** [comment] 2020-06-29 20:59
Duplicate of #2

**Closed by wrxck** 2020-06-29 20:59 UTC
